### ISSUE TITLE
App is showing all collections instead of those with "highlight" checked

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/product-highlights#3]
**Describe the bug**
Hi! We added the product-hightligts app, but the app is rendering all the collections instead of the highlighted ones.

**To Reproduce**

1. Use code in product context:

```js
"vtex.product-highlights@1.x:product-highlights": {
    "props":{
      "type": "collection"
    },
    "children": ["product-highlight-text#colectii"]
  },
  "product-highlight-text#colectii": {
    "props": {
      "message": "{highlightName}",
      "blockClass":"highlightColectie"
    }
  },
```
2. Add 5 collections in admin and add one product in them. Check "highlight" on just one of them

**Expected behavior**
Only the collection name that has highlight in it should be displayed. If we use a filter, it works, but we have dynamic collections that are being created by the marketing team and we can't specify them ahead of time.

```js
"filter": {
        "type": "show",
        "highlightNames": ["Nou","NOU!"]
      }
```

"Nou" and "NOU!" are collections already defined, but we need to render all collections that have highlight on them.

**Screenshots**
![image](https://user-images.githubusercontent.com/42587916/93989252-57e68880-fd92-11ea-8b23-f095140345ec.png)

**Additional context**
Test workpsace: https://doru--fstudio.myvtex.com/aparate-foto/aparate-foto-dslr

**Comment by klzns** [comment]
Fixed on https://github.com/vtex-apps/product-highlights/pull/4

Keep in mind that we bumped a major version so you might need to update the manifest and the blocks, like:

https://github.com/vtex-apps/product-highlights/pull/5/files

**Comment by klzns** [comment]
Btw, thanks for catching this!
